# Generated by Django 5.2.12 on 2026-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("instagram", models.CharField(max_length=100)),
                ("website", models.CharField(max_length=100)),
                ("profile", models.ImageField(upload_to="profile/")),
                ("qr_code", models.ImageField(blank=True, null=True, upload_to="qr/")),
            ],
        ),
    ]
